name: Release

on: [ push ]

env:
  MODULE_NAME: imops

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macOS-11 ]

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0
      - name: Install gcc for mac
        if: matrix.os == 'macOS-11'
        run: |
          echo $PATH
          ln -sf /usr/local/bin/gcc-12 /usr/local/bin/gcc
          ls /usr/local/bin/gcc*
          gcc --version
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_MACOS: >
            PATH="/usr/local/opt/llvm/bin:$PATH" LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include -fopenmp"
          CIBW_BUILD: cp310-*
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    needs: [ check_version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
      - name: Build
        run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
