name: Release

on:
  release:
    types: [ released ]

env:
  MODULE_NAME: imops

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - id: get_version
        name: Get the release version
        uses: Simply007/get-version-action@v2

      - name: Check the version
        run: |
          RELEASE=${{ steps.get_version.outputs.version-without-v }}
          VERSION=$(python -c "from pathlib import Path; import runpy; folder, = {d.parent for d in Path().resolve().glob('*/__init__.py') if d.parent.is_dir() and (d.parent / '__version__.py').exists()}; print(runpy.run_path(folder / '__version__.py')['__version__'])")
          MATCH=$(pip index versions $MODULE_NAME | grep "Available versions:" | grep $VERSION) || echo
          echo $MATCH
          if [ "$GITHUB_BASE_REF" = "master" ] && [ "$MATCH" != "" ]; then echo "Version $VERSION already present" && exit 1; fi
          if [ "$VERSION" != "$RELEASE" ]; then echo "$VERSION vs $RELEASE" && exit 1; fi

  build_wheels:
    uses: ./.github/workflows/build-wheels.yml
    needs: [ check_version ]
    with:
      cibw_build: cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*
      upload_artifacts: true

  build_sdist:
    uses: ./.github/workflows/build-sdist.yml
    needs: [ check_version ]
    with:
      upload_artifacts: true

  release:
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten dist directory
        run: |
          shopt -s globstar
          mkdir -p flat
          cp dist/**/* flat/ || true
          rm -rf dist
          mv flat dist

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
