name: Test build

on: [ pull_request ]

jobs:
  build_wheels:
    uses: ./.github/workflows/build-wheels.yml
    with:
      cibw_build: cp37-* cp39-* cp312-*
      cibw_skip: "*manylinux_x86_64"
      upload_artifacts: false