name: Test build

on: [ pull_request ]

env:
  MODULE_NAME: imops

jobs:
  check_version:
    uses: ./.github/workflows/check-version.yml

  build_wheels:
    uses: ./.github/workflows/build-wheels.yml
    needs: [ check_version ]
    with:
      cibw_build: cp37-* cp39-* cp312-*
      cibw_skip: "*manylinux_x86_64 *musllinux_x86_64"
      upload_artifacts: true

  build_sdist:
    uses: ./.github/workflows/build-sdist.yml
    needs: [ check_version ]
    with:
      upload_artifacts: true

  publish_testpypi:
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten dist directory
        run: |
          shopt -s globstar
          mkdir -p flat
          cp dist/**/* flat/ || true
          rm -rf dist
          mv flat dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true